language: csharp
services:
    - docker
before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
    - docker build --no-cache -t cruz82/dotnetcontainer .
    - docker push cruz82/dotnetcontainer